#!/data/data/com.termux/files/usr/bin/bash
set -e

PREFIX="/data/data/com.termux/files/usr"


case "$1" in
    remove|upgrade|deconfigure)
        [ -L "$PREFIX/bin/termuxify" ] && rm -f "$PREFIX/bin/termuxify"
        [ -f "$PREFIX/bin/termuxify.sh" ] && rm -f "$PREFIX/bin/termuxify.sh"
    ;;
    failed-upgrade)
    ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0
